insert into adega.Regiao values
	("123","sulbrasil","fria"),
    ("456","argentina","temperado"),
    ("789","nortebrasil","semiumido"),
    ("147","sulitalia","continental"),
    ("258","japão","temperado");
    
insert into adega.Vinicola values
	("369","Tannat","origem francesa","5599456199","t@email.com","123"),
    ("321","Merlot","vinhos tintos","5544339912","m@email.com","456"),
    ("654","Malbec"," aroma frutado","5544889912","ma@email.com","789"),
    ("987","Pinot Noir","acidez brilhante","5599887745","p@email.com","147"),
    ("741","Chardonnay","sabor diferente","5514236978","c@email.com","258");
    
insert into adega.Vinho values
	("852","baron","tinto","2019","leve e frutado","369"),
    ("963","solear","tinto","2020","uvas de alta qualidade","321"),
    ("159","zuccardi","tinto","2019","Exuberantes aromas de cerejas","654"),
    ("357","alisios","tinto","2020","toque de caramelo e chocolate","987"),
    ("426","louisjadot","branco","2015","fresca, fina e mineral","741");
	
    
    
